import type { Agent } from '@/types'
import { parseUnits } from 'ethers'

export const MOCK_AGENTS: Agent[] = [
  {
    id: 1n,
    provider: '0x7aF3b12c9d8E4F5a6B7C8D9E0F1a2B3c4D5e6F7',
    metadataURI: JSON.stringify({
      name: 'GPT-4 Code Architect',
      description: 'Advanced AI coding assistant powered by GPT-4. Specializes in full-stack development, code review, debugging, and architecture design. Supports 50+ programming languages with context-aware suggestions.',
      category: 'Coding Assistant',
      image: '',
    }),
    accessInfo: 'https://api.example.com/gpt4-code',
    pricePerPeriod: parseUnits('25', 6),
    periodDuration: BigInt(30 * 86400),
    isPaused: false,
    totalRatings: 89n,
    ratingCount: 20n,
  },
  {
    id: 2n,
    provider: '0x91BcA2d3e4F5a6B7C8D9E0F1a2B3c4D5e6F7a8',
    metadataURI: JSON.stringify({
      name: 'DALL-E Vision Pro',
      description: 'State-of-the-art image generation agent. Creates photorealistic images, concept art, UI mockups, and marketing materials from text prompts. Supports batch generation and style transfer.',
      category: 'Image Generation',
      image: '',
    }),
    accessInfo: 'https://api.example.com/dalle-vision',
    pricePerPeriod: parseUnits('40', 6),
    periodDuration: BigInt(7 * 86400),
    isPaused: false,
    totalRatings: 56n,
    ratingCount: 14n,
  },
  {
    id: 3n,
    provider: '0xB3Cd4E5f6A7B8c9D0e1F2a3B4c5D6e7F8a9B0c',
    metadataURI: JSON.stringify({
      name: 'DataMind Analytics',
      description: 'Powerful data analysis agent that processes CSV, JSON, and SQL datasets. Generates visualizations, statistical summaries, trend analysis, and predictive models automatically.',
      category: 'Data Analysis',
      image: '',
    }),
    accessInfo: 'https://api.example.com/datamind',
    pricePerPeriod: parseUnits('15', 6),
    periodDuration: BigInt(14 * 86400),
    isPaused: false,
    totalRatings: 28n,
    ratingCount: 7n,
  },
  {
    id: 4n,
    provider: '0xD4Ef5A6b7C8d9E0f1A2b3C4d5E6f7A8b9C0d1E',
    metadataURI: JSON.stringify({
      name: 'LinguaFlow Translator',
      description: 'Real-time AI translation agent supporting 120+ languages. Context-aware translations for documents, conversations, and technical content. Preserves tone, idioms, and formatting.',
      category: 'Translation',
      image: '',
    }),
    accessInfo: 'https://api.example.com/linguaflow',
    pricePerPeriod: parseUnits('10', 6),
    periodDuration: BigInt(30 * 86400),
    isPaused: true,
    totalRatings: 12n,
    ratingCount: 4n,
  },
  {
    id: 5n,
    provider: '0xE5Fg6B7c8D9e0F1a2B3c4D5e6F7a8B9c0D1e2F',
    metadataURI: JSON.stringify({
      name: 'ResearchBot Pro',
      description: 'Academic and market research agent. Scours databases, papers, and web sources to compile comprehensive reports. Supports citation formatting, literature reviews, and competitive analysis.',
      category: 'Research',
      image: '',
    }),
    accessInfo: 'https://api.example.com/researchbot',
    pricePerPeriod: parseUnits('50', 6),
    periodDuration: BigInt(30 * 86400),
    isPaused: false,
    totalRatings: 45n,
    ratingCount: 9n,
  },
  {
    id: 6n,
    provider: '0x7aF3b12c9d8E4F5a6B7C8D9E0F1a2B3c4D5e6F7',
    metadataURI: JSON.stringify({
      name: 'SupportGenie AI',
      description: 'Intelligent customer support agent with multi-channel integration. Handles tickets, live chat, FAQ generation, and sentiment analysis. Learns from your knowledge base for accurate responses.',
      category: 'Customer Support',
      image: '',
    }),
    accessInfo: 'https://api.example.com/supportgenie',
    pricePerPeriod: parseUnits('35', 6),
    periodDuration: BigInt(30 * 86400),
    isPaused: false,
    totalRatings: 34n,
    ratingCount: 8n,
  },
]
